INSERT INTO CLIENT (NAME, PIB, EXTERNALUNIQUEKEY, TELEPHONE, EMAIL, ADDRESS, CREATEDON, UPDATEDON, STATUS, BANKACCOUNT)
VALUES ('Firma 1', '3129', '9403D30L', '021223218', 'firma1@gmail.com', 'Kisacka 111' ,'2017-03-03', '2017-04-04', 'BUYER', '3902903223');


INSERT INTO APP_USER (FIRSTNAME, LASTNAME, USERNAME, USER_PASSWORD, EMAIL, TELEPHONE, CLIENT_ID) VALUES ('Milos', 'Ivanovic', 'milos33@gmail.com', 'asd', 'milos33@gmail.com', '3231232', 1);
INSERT INTO APP_USER (FIRSTNAME, LASTNAME, USERNAME, USER_PASSWORD, EMAIL, TELEPHONE, CLIENT_ID) VALUES ('Milos', 'Ivanovic', 'milos34@gmail.com', 'asd', 'milos33@gmail.com', '3231232', 1);
INSERT INTO APP_USER (FIRSTNAME, LASTNAME, USERNAME, USER_PASSWORD, EMAIL, TELEPHONE, CLIENT_ID) VALUES ('Milos', 'Ivanovic', 'milos35@gmail.com', 'asd', 'milos33@gmail.com', '3231232', 1);
INSERT INTO APP_USER (FIRSTNAME, LASTNAME, USERNAME, USER_PASSWORD, EMAIL, TELEPHONE, CLIENT_ID) VALUES ('Milos', 'Ivanovic', 'milos36@gmail.com', 'asd', 'milos33@gmail.com', '3231232', 1);
INSERT INTO APP_USER (FIRSTNAME, LASTNAME, USERNAME, USER_PASSWORD, EMAIL, TELEPHONE, CLIENT_ID) VALUES ('Milos', 'Ivanovic', 'milos38@gmail.com', 'asd', 'milos33@gmail.com', '3231232', 1);
INSERT INTO APP_USER (FIRSTNAME, LASTNAME, USERNAME, USER_PASSWORD, EMAIL, TELEPHONE, CLIENT_ID) VALUES ('Milos', 'Ivanovic', 'milos37@gmail.com', 'asd', 'milos33@gmail.com', '3231232', 1);
INSERT INTO APP_USER (FIRSTNAME, LASTNAME, USERNAME, USER_PASSWORD, EMAIL, TELEPHONE, CLIENT_ID) VALUES ('Milos', 'Ivanovic', 'milos39@gmail.com', 'asd', 'milos33@gmail.com', '3231232', 1);
INSERT INTO APP_USER (FIRSTNAME, LASTNAME, USERNAME, USER_PASSWORD, EMAIL, TELEPHONE, CLIENT_ID) VALUES ('Milos', 'Ivanovic', 'milos40@gmail.com', 'asd', 'milos33@gmail.com', '3231232', 1);
INSERT INTO APP_USER (FIRSTNAME, LASTNAME, USERNAME, USER_PASSWORD, EMAIL, TELEPHONE, CLIENT_ID) VALUES ('Milos', 'Ivanovic', 'milos31@gmail.com', 'asd', 'milos33@gmail.com', '3231232', 1);

INSERT INTO MEASURE (NAME, SHORTCUT) VALUES ('Komad', 'kom');
INSERT INTO MEASURE (NAME, SHORTCUT) VALUES ('Kilogram', 'kg');
INSERT INTO MEASURE (NAME, SHORTCUT) VALUES ('Litar', 'l');
INSERT INTO MEASURE (NAME, SHORTCUT) VALUES ('Gram', 'g');

INSERT INTO TAX (NAME, BASE) VALUES ('10%', 10.00);
INSERT INTO TAX (NAME, BASE) VALUES ('20%', 20.00);

INSERT INTO ITEM (EXTERNALKEY, NAME, PURCHESEPRICE, SELLINGPRICE, MEASURE_ID, TAX_ID) VALUES ('euk-1', 'Cokolada', 89.00, 92.00, 1, 2);
INSERT INTO ITEM (EXTERNALKEY, NAME, PURCHESEPRICE, SELLINGPRICE, MEASURE_ID, TAX_ID) VALUES ('euk-2', 'Keks', 89.00, 92.00, 1, 2);
INSERT INTO ITEM (EXTERNALKEY, NAME, PURCHESEPRICE, SELLINGPRICE, MEASURE_ID, TAX_ID) VALUES ('euk-3', 'Sladoled', 35.00, 40.50, 1, 2);
INSERT INTO ITEM (EXTERNALKEY, NAME, PURCHESEPRICE, SELLINGPRICE, MEASURE_ID, TAX_ID) VALUES ('euk-4', 'Praline', 111.00, 112.00, 1, 2);
INSERT INTO ITEM (EXTERNALKEY, NAME, PURCHESEPRICE, SELLINGPRICE, MEASURE_ID, TAX_ID) VALUES ('euk-5', 'Deodorant', 230.00, 245.00, 1, 2);
INSERT INTO ITEM (EXTERNALKEY, NAME, PURCHESEPRICE, SELLINGPRICE, MEASURE_ID, TAX_ID) VALUES ('euk-6', 'Kuglica', 121.00, 127.00, 1, 2);
INSERT INTO ITEM (EXTERNALKEY, NAME, PURCHESEPRICE, SELLINGPRICE, MEASURE_ID, TAX_ID) VALUES ('euk-7', 'Safun', 89.00, 100.00, 1, 2);
INSERT INTO ITEM (EXTERNALKEY, NAME, PURCHESEPRICE, SELLINGPRICE, MEASURE_ID, TAX_ID) VALUES ('euk-8', 'Cvet', 126.00, 145.00, 1, 2);
