package com.transion.backend.util;

public enum ImportEnum {
	CLIENT_NAME,
	CLIENT_PIB,
	CLIENT_EXTERNALUNIQUEKEY,
	CLIENT_TELEPHONE,
	CLIENT_EMAIL,
	CLIENT_ADDRESS,
	CLIENT_RESPONSIBLEUSER,
	TRANSACTION_LASTDAYTOPAY,
	TRANSACTION_PAYDATE,
	TRANSACTION_DELAY,
	TRANSACTION_AMOUNT,
	TRANSACTION_TRANSACTIONSTATUS,
	TRANSACTION_CLIENT,
	TRANSACTION_STATUS
}
